AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "docker-test"

################################################################################
#                              ECR                                             #
################################################################################

hydraTef:
  Type: AWS::ECR::Repository
  Properties:
    RepositoryName: "docker/test"
    RepositoryPolicyText:
      Version: "2012-10-17"
      Statement:
        Effect: Allow
        Principal:
          AWS:
            - arn:aws:iam::${AWS::AccountId}:role/${ECSRole}
        Action:
          - "ecr:GetDownloadUrlForLayer"
          - "ecr:BatchGetImage"
          - "ecr:BatchCheckLayerAvailability"
          - "ecr:PutImage"
          - "ecr:InitiateLayerUpload"
          - "ecr:UploadLayerPart"
          - "ecr:CompleteLayerUpload"
